routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BusinessController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');


Route::prefix('/')->middleware(['auth'])->group(function () {
    Route::view('dashboard','dashboard')->name('dashboard');
    
    Route::post('/mail', [App\Http\Controllers\ConfigsController::class, 'mail'])->name('settings.mail');
    Route::post('users/{id}/update-password', [App\Http\Controllers\UsersController::class, 'updatePassword'])->name('update.password');
    Route::get('/activity-log', [App\Http\Controllers\ActivityLogController::class, 'index'])->name('activity-log.index');
    Route::resource('/users', App\Http\Controllers\UsersController::class);
    Route::get('users/trash/soft', [App\Http\Controllers\UsersController::class, 'trash'])->name('users.trash');
    Route::get('users/restore/{id}', [App\Http\Controllers\UsersController::class, 'restore'])->name('users.restore');
    Route::get('users/trash/restore', [App\Http\Controllers\UsersController::class, 'restoreAll'])->name('users.restoreAll');
    Route::post('users/force-delete/{id}', [App\Http\Controllers\UsersController::class, 'forceDelete'])->name('users.forceDelete');
    Route::get('download/data-pengguna', [App\Http\Controllers\UsersController::class, 'UserExport'])->name('UserExport');
    Route::resource('/roles', App\Http\Controllers\RolesController::class);
    Route::resource('/settings', App\Http\Controllers\ConfigsController::class);
    
    
    // LOGIN SEBAGAI USER LAIN
    Route::get('users/login-as/{id}', [App\Http\Controllers\UserAccessController::class, 'loginAs'])->name('user.login-as');

    // ============================================JLA===================================================
    Route::get('/flowchart',[App\Http\Controllers\HarianLepasController::class, 'flowchart'])->name('flowchart');
    // master hrd
    Route::resource('/master-departemen', App\Http\Controllers\MasterDepartemenController::class);
    Route::resource('/master-bagian', App\Http\Controllers\MasterBagianController::class);
    Route::resource('/harian-lepas', App\Http\Controllers\HarianLepasController::class);

    // master harian proses
    Route::resource('/master-item', App\Http\Controllers\MasterItemController::class);
    Route::resource('/master-keterangan-bahan', App\Http\Controllers\MasterKeteranganBahanController::class);
    Route::resource('/master-type-bahan', App\Http\Controllers\MasterTypeBahanController::class);
    Route::resource('/master-warna', App\Http\Controllers\MasterWarnaController::class);
    Route::resource('/master-group-kualitas', App\Http\Controllers\MasterGroupKualitasController::class);
    Route::resource('/master-kualitas', App\Http\Controllers\MasterKualitasController::class);
    Route::resource('/master-jenis-kayu', App\Http\Controllers\MasterJenisKayuController::class);
    Route::resource('/master-keterangan-proses', App\Http\Controllers\MasterKeteranganProsesController::class);
    Route::resource('/master-departemen-harian-proses', App\Http\Controllers\MasterDepartemenHarianProsesController::class);
    Route::resource('/master-unit', App\Http\Controllers\MasterUnitController::class);
    Route::resource('/master-sub-unit', App\Http\Controllers\MasterSubUnitController::class);
    Route::resource('/master-supplier', App\Http\Controllers\MasterSupplierController::class);
    Route::resource('/master-product', App\Http\Controllers\MasterProductController::class);
    Route::resource('/master-no-po', App\Http\Controllers\MasterNoPoController::class);
    Route::resource('/master-pemborong', App\Http\Controllers\MasterPemborongController::class);
    Route::resource('/master-jenis-pekerjaan', App\Http\Controllers\MasterJenisPekerjaanController::class);
    Route::resource('/master-keterangan-pekerjaan', App\Http\Controllers\MasterKeteranganPekerjaanController::class);
    Route::resource('/master-lokasi', App\Http\Controllers\MasterLokasiController::class);
    Route::resource('/master-shift', App\Http\Controllers\MasterShiftController::class);
    Route::resource('/master-tenaga-kerja', App\Http\Controllers\MasterTenagaKerjaController::class);
    Route::resource('/master-status-tenaga-kerja', App\Http\Controllers\MasterStatusTenagaKerjaController::class);
    
    //fitur harian proses
    Route::resource('/item', App\Http\Controllers\ItemController::class);
    Route::resource('/input-harian', App\Http\Controllers\InputHarianController::class);
    // Route::get('/json-input-harian',[App\Http\Controllers\InputHarianController::class, 'json_departemen'])->name('input-harian.json-departemen');
    Route::post('/json-input-harian-departemen',[App\Http\Controllers\InputHarianController::class, 'json_departemen'])->name('input-harian.json-departemen');
    Route::post('/json-input-harian-unit',[App\Http\Controllers\InputHarianController::class, 'json_unit'])->name('input-harian.json-unit');
    Route::post('/input/history',[App\Http\Controllers\InputHarianController::class, 'history'])->name('input-harian.history');
    Route::post('/input/history/list-item',[App\Http\Controllers\InputHarianController::class, 'list_item'])->name('input-harian.list');
    Route::post('/input/history/list-item/form',[App\Http\Controllers\InputHarianController::class, 'input_harian'])->name('input-harian.input');
    Route::get('/json-item',[App\Http\Controllers\InputHarianController::class, 'json_item'])->name('input-harian.json-item');
    Route::resource('/input-harian-in', App\Http\Controllers\InputHarianInController::class);
    Route::resource('/input-harian-out', App\Http\Controllers\InputHarianOutController::class);

});

resources/views/pages/harian-proses/outs/delete.blade.php
<div class="modal fade" id="modal-info-confirmed" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 500px">
        <div class="modal-content position-relative">
            <div class="position-absolute top-0 end-0 mt-2 me-2 z-index-1">
                <button class="btn-close btn btn-sm btn-circle d-flex flex-center transition-base" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <div class="rounded-top-lg py-3 ps-4 pe-6 bg-light">
                    <h4 class="mb-1">Hapus Data</h4>
                </div>
                <div class="p-4 pb-0">
                    <p>Apakah Anda yakin ingin menghapus data?</p> 
                </div>
            </div>
            <div class="modal-footer">
                <input type="hidden" name="id" id="id">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-danger text-uppercase"  id="change" onclick="destroy()">
                    Hapus
                </button>
            </div>
        </div>
    </div>
</div>

<script>

    function remove(id){
        $('#id').val(id);

    }

    function destroy(){
        var id =$('#id').val();

        createOverlay("process...");
        $.ajax({
            type: 'DELETE',
            dataType: 'json',
            data: {
                '_token' : '{{ csrf_token() }}',
                id: id,
            },
            url: "/input-harian-out/"+id,
            
            success: function(data){
                gOverlay.hide();

                if(data["status"] == "success") {            
                    toastr.success(data["message"]);
                    setTimeout(function(){ 
                        window.location = "{{route('input-harian-out.index')}}";
                    }, 500);            
                }else {
                    toastr.error(data["message"]);
                }
            },
            error: function(error) {
                alert("Server/network error\r\n" + error);
            }
        });
    }


</script>

resources/views/pages/harian-proses/outs/index.blade.php
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<x-app-layout>
   <div class="col-lg-12">
      <div class="card">
         <div class="card-header border-bottom">
            <div class="row flex-between-end">
               <div class="col-auto align-self-center">
                  <h5 class="mb-0" data-anchor="data-anchor">Input Harian Out</h5>
               </div>
               
               <div class="col-auto ms-auto">
                  <div class="nav nav-pills nav-pills-falcon flex-grow-1 mt-2" role="tablist">
                     <form action="{{ route('input-harian-out.index') }}" method="GET" class="d-flex align-items-center add-contact__form my-sm-0 my-2">
                        <span data-feather="search"></span>
                        <input class="form-control mr-sm-2 border-0 box-shadow-none" name="search" value="{{ request('search') }}" type="search" id="userName" onkeyup="userFunction()" placeholder="Pencarian" aria-label="Search">
                     </form>
                  </div>
               </div>
            </div>
         </div>
         <div class="card-body pt-0">
            <div class="tab-content">
               <div class="tab-pane preview-tab-pane active" role="tabpanel" aria-labelledby="tab-dom-6fa4c848-cf7f-4ed7-bab0-9326a3ce9502" id="dom-6fa4c848-cf7f-4ed7-bab0-9326a3ce9502">
                  <div class="table-responsive scrollbar">
                     <table class="table">
                        <thead>
                           <tr>
                              <th style="width: 10%;">No</th>
                              <th scope="col">Tanggal</th>
                              <th scope="col">No_Process</th>
                              <th scope="col">Departemen</th>
                              <th scope="col">Unit</th>
                              <th scope="col">Sub_Unit</th>
                              <th scope="col">No_Part_Item</th>
                              <th scope="col">Item</th>
                              <th scope="col">Shift</th>
                              <th scope="col">Keterangan_Bahan</th>
                              <th scope="col">Type_Bahan</th>
                              <th scope="col">Jenis_Kayu</th>
                              <th scope="col">Group_Kualitas</th>
                              <th scope="col">Kualitas</th>
                              <th scope="col">Warna</th>
                              <th scope="col">Diameter</th>
                              <th scope="col">Keterangan_Proses</th>
                              <th scope="col">Tinggi</th>
                              <th scope="col">Lebar</th>
                              <th scope="col">Panjang</th>
                              <th scope="col">Pcs</th>
                              <th scope="col">M1</th>
                              <th scope="col">M2</th>
                              <th scope="col">M3</th>
                              <th scope="col">Suppliers</th>
                              <th scope="col">No_Kiriman</th>
                              <th scope="col">Products</th>
                              <th scope="col">No_Po</th>
                              <th scope="col">No_Pallet</th>
                              <th scope="col">Nampan</th>
                              <th scope="col">Operator</th>
                              <th scope="col">Harian_Tetap</th>
                              <th scope="col">Harian_Lepas</th>
                              <th scope="col">Borong</th>
                              <th scope="col">Pemborong</th>
                              <th scope="col">Memo</th>
                              <th scope="col">OT</th>
                              <th scope="col">Tahun</th>
                              <th scope="col">Keterangan</th>
                              <th scope="col">Created_At</th>
                              <th class="text-end" scope="col">Actions</th>
                           </tr>
                        </thead>
                        <tbody>
                           @foreach($outs as $item)
                              <tr>
                                 <td>{{ $loop->iteration }}</td>
                                 <td>{{\Carbon\Carbon::parse($item->tanggal)->format('d M Y')}}</td>
                                 <td>{{ $item->no_process }}</td>
                                 <td>{{ $item->departemen }}</td>
                                 <td>{{ $item->unit }}</td>
                                 <td>{{ $item->sub_unit }}</td>
                                 <td>{{ $item->no_part_item }}</td>
                                 <td>{{ $item->item }}</td>
                                 <td>{{ $item->master_shift->name }}</td>
                                 <td>{{ $item->keterangan_bahan }}</td>
                                 <td>{{ $item->type_bahan }}</td>
                                 <td>{{ $item->jenis_kayu }}</td>
                                 <td>{{ $item->group_kualitas }}</td>
                                 <td>{{ $item->kualitas }}</td>
                                 <td>{{ $item->warna }}</td>
                                 <td>{{ $item->diameter }}</td>
                                 <td>{{ $item->keterangan_proses }}</td>
                                 <td>{{ $item->tinggi }}</td>
                                 <td>{{ $item->lebar }}</td>
                                 <td>{{ $item->panjang }}</td>
                                 <td>{{ $item->pcs }}</td>
                                 <td>{{ $item->m1 }}</td>
                                 <td>{{ $item->m2 }}</td>
                                 <td>{{ $item->m3 }}</td>
                                 <td>{{ $item->suppliers->name  }}</td>
                                 <td>{{ $item->no_kiriman }}</td>
                                 <td>{{ $item->product->name  }}</td>
                                 <td>{{ $item->no_product->name  }}</td>
                                 <td>{{ $item->no_pallet }}</td>
                                 <td>{{ $item->nampan }}</td>
                                 <td>{{ $item->operator }}</td>
                                 <td>{{ $item->harian_tetap }}</td>
                                 <td>{{ $item->harian_lepas }}</td>
                                 <td>{{ $item->borong }}</td>
                                 <td>{{ $item->pemborong->name  }}</td>
                                 <td>{{ $item->memo }}</td>
                                 <td>
                                    @if ($item->ot == 1)
                                       Ada
                                    @else
                                       Tidak Ada
                                    @endif
                                 </td>
                                 <td>{{ $item->tahun }}</td>
                                 <td>{{ $item->keterangan }}</td>
                                 <td>{{\Carbon\Carbon::parse($item->created_at)->format('d M Y')}}</td>
                                 <td class="text-end">
                                    <div>
                                       <button class="btn p-0" type="button" onClick="edit({{ json_encode($item) }})" title="Edit" data-bs-toggle="modal" data-bs-target="#item-modal"><span class="text-500 fas fa-edit"></span></button>
                                       <button class="btn p-0 ms-2" type="button" onClick="remove({{ json_encode($item->id) }})" title="Delete" data-bs-toggle="modal" data-bs-target="#modal-info-confirmed"><span class="text-500 fas fa-trash-alt"></span></button>
                                    </div>
                                 </td>
                              </tr>
                           @endforeach
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   @include('pages.harian-proses.outs.modal')
   @include('pages.harian-proses.outs.delete')
</x-app-layout>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

resources/views/pages/harian-proses/outs/modal.blade.php
<div class="modal fade" id="item-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document" style="max-width: 500px">
        <div class="modal-content position-relative">
            <div class="position-absolute top-0 end-0 mt-2 me-2 z-index-1">
                <button class="btn-close btn btn-sm btn-circle d-flex flex-center transition-base" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body p-0">
                <div class="rounded-top-lg py-3 ps-4 pe-6 bg-light">
                    <h4 class="mb-1" id="modal-title"></h4>
                </div>
                <div class="p-4 pb-0">
                    <form id="form" action="#">
                        <input type="hidden" class="form-control" id="id" disabled>
                        <div class="mb-3">
                            <label class="col-form-label" for="shift">Shift:</label>
                            <select class="form-control" id="shift" name="shift">
                                <option value="">Pilih</option>
                                @foreach ($shift as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="pcs">Pcs:</label>
                            <input type="number" class="form-control" id="pcs">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="supplier">Supplier:</label>
                            <select class="form-control" id="supplier" name="supplier">
                                <option value="">Pilih</option>
                                @foreach ($supplier as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="no_kiriman">No Kiriman:</label>
                            <input type="number" class="form-control" id="no_kiriman">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="po">PO:</label>
                            <select class="form-control" id="po" name="po">
                                <option value="">Pilih PO</option>
                                @foreach ($product as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="po_no">PO Nomer:</label>
                            <select class="form-control" id="po_no" name="po_no">
                                <option value="">Pilih PO Nomer</option>
                                @foreach ($no_po as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="no_pallet">No Pallet:</label>
                            <input type="number" class="form-control" id="no_pallet">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="nampan">Nampan:</label>
                            <input type="number" class="form-control" id="nampan">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="operator">Operator:</label>
                            <input type="text" class="form-control" id="operator">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="harian_tetap">Harian Tetap:</label>
                            <input type="number" class="form-control" id="harian_tetap">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="harian_lepas">Harian Lepas:</label>
                            <input type="number" class="form-control" id="harian_lepas">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="borong">Borong:</label>
                            <input type="number" class="form-control" id="borong">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="pemborong">Pemborong:</label>
                            <select class="form-control" id="pemborong" name="pemborong">
                                <option value="">Pilih</option>
                                @foreach ($pemborong as $item)
                                    <option value="{{$item->id}}">{{$item->name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="memo">Memo:</label>
                            <input type="text" class="form-control" id="memo">
                        </div>
                        <div class="mb-3">
                            <label class="col-form-label" for="ot">Ot:</label>
                            <select class="form-control" id="ot" name="ot">
                                <option value="">Pilih</option>
                                <option value="1">Ada</option>
                                <option value="2">Tidak Ada</option>
                            </select>
                        </div>
                        {{-- <div class="mb-3">
                            <div class="tab-pane preview-tab-pane active" role="tabpanel" aria-labelledby="tab-dom-e0d869aa-3441-496b-9fc3-0333faf70522" id="dom-e0d869aa-3441-496b-9fc3-0333faf70522">
                                <div class="form-check">
                                    <input class="form-check-input" id="flexRadioDefault1" type="radio" id="ot" name="ot" value="1"/>
                                    <label class="form-check-label" for="flexRadioDefault1">Ada</label>
                                </div>
                                <div class="form-check">
                                    <input class="form-check-input" id="flexRadioDefault2" type="radio" id="ot" name="ot" value="2" checked/>
                                    <label class="form-check-label" for="flexRadioDefault2">Tidak Ada</label>
                                </div>
                            </div>
                        </div> --}}
                        <div class="mb-3">
                            <label class="col-form-label" for="keterangan">Keterangan:</label>
                            <input type="text" class="form-control" id="keterangan">
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-bs-dismiss="modal">Close</button>
                <button class="btn btn-primary" type="button" id="update" onclick="updated()">Update</button>
            </div>
        </div>
    </div>
</div>

<script>
    function edit(data){
        // console.log(data.ot);

        $('#form').trigger("reset");
        $('#modal-title').text('Edit Data');
        $('#id').val(data.id);
        $('#shift').val(data.shift);
        $('#pcs').val(data.pcs);
        $('#supplier').val(data.master_suppliers_id);
        $('#no_kiriman').val(data.no_kiriman);
        $('#po').val(data.master_products_id);
        $('#po_no').val(data.master_no_pos_id);
        $('#no_pallet').val(data.no_pallet);
        $('#nampan').val(data.nampan);
        $('#operator').val(data.operator);
        $('#harian_tetap').val(data.harian_tetap);
        $('#harian_lepas').val(data.harian_lepas);
        $('#borong').val(data.borong);
        $('#pemborong').val(data.master_pemborongs_id);
        $('#memo').val(data.memo);
        $('#ot').val(data.ot);
        $('#keterangan').val(data.keterangan);
        $("#update").show();
        $('#modal-basic').modal('show');
    }

    function updated(){
        var id = $('#id').val();
        var shift = $('#shift').val();
        var pcs = $('#pcs').val();
        var supplier = $('#supplier').val();
        var no_kiriman = $('#no_kiriman').val();
        var po = $('#po').val();
        var po_no = $('#po_no').val();
        var no_pallet = $('#no_pallet').val();
        var nampan = $('#nampan').val();
        var operator = $('#operator').val();
        var harian_tetap = $('#harian_tetap').val();
        var harian_lepas = $('#harian_lepas').val();
        var borong = $('#borong').val();
        var pemborong = $('#pemborong').val();
        var memo = $('#memo').val();
        var ot = $('#ot').val();
        var keterangan = $('#keterangan').val();
        createOverlay("Proses...");
        $.ajax({
            type : "PUT",
            url: "{!! route('input-harian-out.update',["id"]) !!}",
            dataType: 'json',
            data: {
                '_token' : '{{ csrf_token() }}',
                'id' : id,
                'shift' :shift,
                'pcs' :pcs,
                'supplier' :supplier,
                'no_kiriman' :no_kiriman,
                'po' :po,
                'po_no' :po_no,
                'no_pallet' :no_pallet,
                'nampan' :nampan,
                'operator' :operator,
                'harian_tetap' :harian_tetap,
                'harian_lepas' :harian_lepas,
                'borong' :borong,
                'pemborong' :pemborong,
                'memo' :memo,
                'ot' :ot,
                'keterangan' :keterangan,
            },
            success: function(data){
                gOverlay.hide();
                if(data["status"] == "success") {            
                    toastr.success(data["message"]);
                    setTimeout(function(){ 
                            window.location = "{{route('input-harian-out.index')}}";
                    }, 500);              
                }else {
                    toastr.error(data["message"]);
                }
            },
            error: function(error) {
                alert("Server/network error\r\n" + error);
            }
        });
    }

</script>